services:
  - type: web
    name: groupie-tracker
    runtime: go
    runtimeVersion: "1.22"
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app main.go database.go auth.go routes.go
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
